stages:
- build

variables:
  POSTGRES_UID: "999"

.build:
  stage: build
  script: 
    - cat $DOCKERPASS | docker login -u 3liz --password-stdin
    - make build push POSTGIS_VER=$POSTGIS_VER POSTGRES_VER=$POSTGRES_VER POSTGRES_UID=$POSTGRES_UID
  tags:
    - factory-dind
  only:
    refs:
      - schedules

build:12-3:
  extends: .build
  variables:
    POSTGIS_VER: "3"
    POSTGRES_VER: "12"

build:13-3:
  extends: .build
  variables:
    POSTGIS_VER: "3"
    POSTGRES_VER: "13"

build:14-3:
  extends: .build
  variables:
    POSTGIS_VER: "3"
    POSTGRES_VER: "14"

build:15-3:
  extends: .build
  variables:
    POSTGIS_VER: "3"
    POSTGRES_VER: "15"

build:16-3:
  extends: .build
  variables:
    POSTGIS_VER: "3"
    POSTGRES_VER: "16"


